### ISSUE TITLE
Long running time

### ISSUE THREAD

**Issue by dweemx** [tatsuro-kawamoto/graphBIX#2]
Hi,
I tried also to run `julia sbm.jl` on the toy dataset available in the repo:
```
julia sbm.jl labeled_sbm/test.txt --q=2:2:6 --init=normalizedLaplacian --initnum=5
```
It's taking quite a while (it's has been running for 6h now and still running)

Is this expected ? If so, Is there a way to fasten the process ?
I'd like to run it on `505950` edges and even more. What do you suggest ?

**Comment by tatsuro-kawamoto** [comment]
The running time depends a lot on the dataset (i.e., the convergence issue). Empirically, `uniformAssortative` works better as the initial condition (`--init` option). 

The size of 505950 edges is not impossible, but considering the fact that the above run tries 15 runs (5 runs for each of 3 choices of num. clusters) of the whole EM algorithm, I can imagine that takes for a while.

**Comment by dweemx** [comment]
Ok thanks for this tip
How much would you suggest minimally for `--initnum` ?

**Comment by tatsuro-kawamoto** [comment]
I would try at least `--initnum = 5`. You should check if you obtain consistent results (i.e., prediction errors and resulting partition) by multiple runs.
